MARKETPLACE_TO_HOSTS = {
    "www.amazon.com.au": "webservices.amazon.com.au",
    "www.amazon.com.br": "webservices.amazon.com.br",
    "www.amazon.ca": "webservices.amazon.ca",
    "www.amazon.fr": "webservices.amazon.fr",
    "www.amazon.de": "webservices.amazon.de",
    "www.amazon.in": "webservices.amazon.in",
    "www.amazon.it": "webservices.amazon.it",
    "www.amazon.co.jp": "webservices.amazon.co.jp",
    "www.amazon.com.mx": "webservices.amazon.com.mx",
    "www.amazon.es": "webservices.amazon.es",
    "www.amazon.com.tr": "webservices.amazon.com.tr",
    "www.amazon.ae": "webservices.amazon.ae",
    "www.amazon.co.uk": "webservices.amazon.co.uk",
    "www.amazon.com": "webservices.amazon.com",
}

HOST_TO_REGIONS = {
    "webservices.amazon.com.au": "us-west-2",
    "webservices.amazon.com.br": "us-east-1",
    "webservices.amazon.ca": "us-east-1",
    "webservices.amazon.fr": "eu-west-1",
    "webservices.amazon.de": "eu-west-1",
    "webservices.amazon.in": "eu-west-1",
    "webservices.amazon.it": "eu-west-1",
    "webservices.amazon.co.jp": "us-west-2",
    "webservices.amazon.com.mx": "us-east-1",
    "webservices.amazon.es": "eu-west-1",
    "webservices.amazon.com.tr": "eu-west-1",
    "webservices.amazon.ae": "eu-west-1",
    "webservices.amazon.co.uk": "eu-west-1",
    "webservices.amazon.com": "us-east-1",
}

OPERATION_TO_PATHS = {
    "GetBrowseNodes": "/paapi5/getbrowsenodes",
    "GetVariations": "/paapi5/getvariations",
    "GetItems": "/paapi5/getitems",
    "SearchItems": "/paapi5/searchitems",
}

RESOURCES = [
    "BrowseNodeInfo.BrowseNodes",
    "BrowseNodeInfo.BrowseNodes.Ancestor",
    "BrowseNodeInfo.BrowseNodes.SalesRank",
    "BrowseNodeInfo.WebsiteSalesRank",
    "CustomerReviews.Count",
    "CustomerReviews.StarRating",
    "Images.Primary.Small",
    "Images.Primary.Medium",
    "Images.Primary.Large",
    "Images.Variants.Small",
    "Images.Variants.Medium",
    "Images.Variants.Large",
    "ItemInfo.ByLineInfo",
    "ItemInfo.ContentInfo",
    "ItemInfo.ContentRating",
    "ItemInfo.Classifications",
    "ItemInfo.ExternalIds",
    "ItemInfo.Features",
    "ItemInfo.ManufactureInfo",
    "ItemInfo.ProductInfo",
    "ItemInfo.TechnicalInfo",
    "ItemInfo.Title",
    "ItemInfo.TradeInInfo",
    "Offers.Listings.Availability.MaxOrderQuantity",
    "Offers.Listings.Availability.Message",
    "Offers.Listings.Availability.MinOrderQuantity",
    "Offers.Listings.Availability.Type",
    "Offers.Listings.Condition",
    "Offers.Listings.Condition.ConditionNote",
    "Offers.Listings.Condition.SubCondition",
    "Offers.Listings.DeliveryInfo.IsAmazonFulfilled",
    "Offers.Listings.DeliveryInfo.IsFreeShippingEligible",
    "Offers.Listings.DeliveryInfo.IsPrimeEligible",
    "Offers.Listings.DeliveryInfo.ShippingCharges",
    "Offers.Listings.IsBuyBoxWinner",
    "Offers.Listings.LoyaltyPoints.Points",
    "Offers.Listings.MerchantInfo",
    "Offers.Listings.Price",
    "Offers.Listings.ProgramEligibility.IsPrimeExclusive",
    "Offers.Listings.ProgramEligibility.IsPrimePantry",
    "Offers.Listings.Promotions",
    "Offers.Listings.SavingBasis",
    "Offers.Summaries.HighestPrice",
    "Offers.Summaries.LowestPrice",
    "Offers.Summaries.OfferCount",
    "ParentASIN",
    "RentalOffers.Listings.Availability.MaxOrderQuantity",
    "RentalOffers.Listings.Availability.Message",
    "RentalOffers.Listings.Availability.MinOrderQuantity",
    "RentalOffers.Listings.Availability.Type",
    "RentalOffers.Listings.BasePrice",
    "RentalOffers.Listings.Condition",
    "RentalOffers.Listings.Condition.ConditionNote",
    "RentalOffers.Listings.Condition.SubCondition",
    "RentalOffers.Listings.DeliveryInfo.IsAmazonFulfilled",
    "RentalOffers.Listings.DeliveryInfo.IsFreeShippingEligible",
    "RentalOffers.Listings.DeliveryInfo.IsPrimeEligible",
    "RentalOffers.Listings.DeliveryInfo.ShippingCharges",
    "RentalOffers.Listings.MerchantInfo",
]
